solids:
  query_omeka:
    config: 
      url: 'https://images.imaginerio.org/api/items'
  query_wikidata:
    config:
      url: 'https://query.wikidata.org/sparql'
      path:
  query_portals:
    config:
      url: 'https://acervos.ims.com.br/CIP/metadata/search/portals-general-access/situatedviews'
      path: data-out/api-portals.csv
       
 


