name: Build IIIF Manifests

on:
  workflow_dispatch:
    inputs:
      index:
        description: 'Index to process (0, 1, 2, etc), leave blank to process all items'
        required: false
        default: ''
    
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Build Docker image
      run: docker build . -t etl

    - name: Run Docker Image
      run: |
        if [ -z "${{ github.event.inputs.index }}" ]; then
          docker run etl
        else
          docker run etl -m imaginerio-etl.scripts.iiif -i ${{ github.event.inputs.index }}
        fi
