name: Update imagineRio

on:
  repository_dispatch:
    types: [submodule-update]
  workflow_dispatch:
    inputs:
      index:
        description: "SSIDs to process (space separated, e.g. '35103808 35103809'), leave blank to process all items"
        required: false
        default: ""
      retile:
        description: "Retile images. Should only be used when specifying ids above"
        type: boolean
        required: false

jobs:
  update-process:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        run: node imaginerio-etl/utils/fetchData.js
        env:
          JSTOR_USER: ${{ secrets.JSTOR_USER }}
          JSTOR_PASSWORD: ${{ secrets.JSTOR_PASSWORD }}
          JSTOR_PROJECT: ${{ secrets.JSTOR_PROJECT }}

      - name: Compare data
        run: |
          pip install pandas xlrd openpyxl
          python3 imaginerio-etl/utils/compare_data.py

      - name: Build Docker image
        run: docker build . -t etl

      - name: Run Docker Image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ARCGIS_USER: ${{ secrets.ARCGIS_USER }}
          ARCGIS_PASSWORD: ${{ secrets.ARCGIS_PASSWORD }}
          VIEWCONES_LAYER_URL: ${{ secrets.VIEWCONES_LAYER_URL }}
        run: |
          ARGS=""
          if [ ! -z "${{ github.event.inputs.index }}" ]; then
            ARGS="-m imaginerio-etl.scripts.iiif -i ${{ github.event.inputs.index }}"
          fi
          if [ "${{ github.event.inputs.retile }}" == "true" ]; then
            ARGS="$ARGS --retile"
          fi
          docker run \
            -e AWS_SECRET_ACCESS_KEY \
            -e AWS_ACCESS_KEY_ID \
            -e ARCGIS_USER \
            -e ARCGIS_PASSWORD \
            -e VIEWCONES_LAYER_URL \
            -v $(pwd)/data:/usr/src/app/data \
            etl $ARGS

      - name: Commit and push changes
        run: |
          cd data
          git config --global user.name 'martimpassos'
          git config --global user.email 'martimpassos@users.noreply.github.com'
          git add .
          if git diff --staged --quiet; then
            echo "No changes detected, skipping commit."
          else
            git commit -m "Update data"
            git push
          fi
          cd ..
          git add data
          if git diff --staged --quiet; then
            echo "No changes detected, skipping commit."
            exit 0
          else
            git commit -m "Update submodule"
            git push
          fi
